name: Movelister

on:
  # Enable to run this action manually.
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LibreOffice and dependencies
      run: sudo apt install libreoffice-base libreoffice libreoffice-script-provider-python uno-libs3 python3-uno
    - name: Print Python version
      run: python3 --version
    - name: Print LibreOffce version
      run: $MV_LB_BIN --version
    - name: Install Python dependencies
      run: |
        pip3 install flake8
    - name: Test
      run: python3 -m unittest
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --statistics
