name: Movelister

on:
  # Enable to run this action manually.
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test Movelister
    runs-on: ubuntu-latest
    env:
      # LibreOffice binary and port used for testing.
      MV_LB_BIN: soffice
      MV_LB_PORT: 8080

    steps:
    - uses: actions/checkout@v2
    - name: Install LibreOffice
      run: sudo apt install libreoffice libreoffice-script-provider-python uno-libs3 python3-uno
    - name: Install Python dependencies
      run: pip3 install flake8
    - name: Print Python version
      run: python3 --version
    - name: Print LibreOffce version
      run: $MV_LB_BIN --version
    - name: Run tests
      run: python3 -m unittest
    - name: Lint
      run: python3 -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
