name: Movelister

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Movelister unit test
    runs-on: ubuntu-latest
    env:
      # Binary to run LibreOffice from the command line.
      MV_LB_BIN : soffice
      MV_LB_PORT: 8080

    steps:
    - uses: actions/checkout@v2
    - name: Install LibreOffice and dependencies
      run: sudo apt install libreoffice-base libreoffice libreoffice-script-provider-python uno-libs3 python3-un
    - name: Print Python version
      run: python3 --version
    - name: Print LibreOffce version
      run: $MV_LB_BIN --version
    - name: Install dependencies
      run: |
        pip3 install flake8
    - name: Test
      run: python3 -m unittest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
